/*
 * Shape options for the intersection of three-way traps.
 */
var TrapEndTypes = {
  /*
   * Shapes the end of the trap to keep it away from the intersecting object.
   * @type {Number}
   */
  MITER_TRAP_ENDS: undefined,
  
  /*
   * Reshapes the trap generated by the lightest neutral density object so that it wraps around the point where the three objects intersect.
   * @type {Number}
   */
  OVERLAP_TRAP_ENDS: undefined,
  
};
